### ISSUE TITLE
Improve Application menu detection w/ fallback options

### ISSUE THREAD

**Issue by rbreaves** [mydockfinder/mydockfinder#257]
I am very impressed with what I have seen, but can we also add in the ability to override or create fallback menus per application?

Suggestion or example would be a yaml formatted file, which can define application menus for as many applications as you want as long as the options have an associated hotkey or Alt key combo path to reach that option.

```
Applications:
  notepad.exe:
    File:
      - New [Ctrl+N]
      - New Window [Ctrl+Shift+N]
      ...
     Edit:
       - Undo [Ctrl+Z]
       ...
  code.exe:
      File:
        - New [Ctrl+N]
        - New Window [Ctrl+Shift+N]
        ...
```

Additionally if we could swap out references to Ctrl, Alt or Shift with symbols such as ⌘, ⌥, ^, or ⇧, then that would be wonderful too.
